### PR TITLE
Add postgresql-devel (pg_config) package

### PR DESCRIPTION
**Pull request by nbetm**
closes https://github.com/Parsely/engineering/issues/4062

### CODE REVIEW

**Comment by nbetm** [comment]
@dan-blanchard ...

```
Building wheels for collected packages: parsely-raw-data, psycopg2cffi-compat, psycopg2
  Building wheel for parsely-raw-data (setup.py): started
  Building wheel for parsely-raw-data (setup.py): finished with status 'done'
  Created wheel for parsely-raw-data: filename=parsely_raw_data-2.3.0-py2.py3-none-any.whl size=21747 sha256=4691cb63b3f36f8eef8508d75ee4f46f473437022069e5a2df6e988b95b88768
  Stored in directory: /root/.cache/pip/wheels/93/58/c5/ffc4063652a2c69bc6e33a2d8420668c88344b2d812ce0a126
  Building wheel for psycopg2cffi-compat (setup.py): started
  Building wheel for psycopg2cffi-compat (setup.py): finished with status 'done'
  Created wheel for psycopg2cffi-compat: filename=psycopg2cffi_compat-1.1-py3-none-any.whl size=1275 sha256=0c56a1e7e18ce30ebadd0afb86c25319296eb1a695fc2c534d99118c206510d3
  Stored in directory: /root/.cache/pip/wheels/5e/af/bf/80317dc5b3276819808ce14dd4926791d30c44aa3d43b62eb6
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.5-cp36-cp36m-linux_x86_64.whl size=463623 sha256=73122c8262282c828ae9bc2a9ed1cb6e805c40bfa805785c0cb8a727de978ec9
  Stored in directory: /root/.cache/pip/wheels/52/9a/ab/22a0d1dc560ad5c0d09cc1c968015f89726e7e01c190dee110
Successfully built parsely-raw-data psycopg2cffi-compat psycopg2
```

**Comment by nbetm** [comment]
it failed on the manylinux1 image. I'll look at this tomorrow!

**Comment by nbetm** [comment]
@dan-blanchard I'm having a hard time installing postgresql libs 9.1 and older on manylinux1 image (Centos5). Question for you, do we still need manylinux1 now that manylinux2010 is out?

**Comment by nbetm** [comment]
I was able to make it work with v9.5 on both CentOS releases. I've uploaded two tgz files to our public bucket so we don't depend on the official yum repository (mainly because CentOS 5 complains about SSL certs)

**Comment by nbetm** [comment]
@dan-blanchard -- all fixed!

**Comment by dan-blanchard** [comment]
Thanks?

**Pull request merged**
